### PR TITLE
"Minor" bugfix in 3dvar layout

### LINKED ISSUE #91: Move all the observation processing from SetupJoCostFunction.sh to Obs_Prep JJOB and scripts

### LINKED ISSUE #93: Error traps in scripts
Currently, a failure in any of the jjobs will not trigger a failure when exiting the scripts.

### LINKED ISSUE #94: Wrong dependency in 3dvar_only.yaml
As currently implemented, da_prep should depend on obs_prep ... Oops. The fact that it works most of the time is that obs_prep runs faster than da_prep, but not always.
Related to #91

### PR DESCRIPTION
**Pull request by guillaumevernieres**
The dependency in the 3dvar layout was wrong. Work done:
- Fix job dependency issue in the 3dvar layout
- Moved obs thinning from "setupJo" to obs prep
- Minor code tidy, debatable if the code is actually tidier!
- Added error traps at the script header level

closes #91 
closes #93 
closes #94

### CODE REVIEW

File: scripts/SetupJoCostFunction.sh [hunk 1]
```diff
@@ -54,15 +54,16 @@ obsfile=$obsdatabase/ioda.icec.cat_l2.emc.${DA_SLOT_LEN}h.nc
...
    # Create record dim
-   ncks --mk_rec_dmn nlocs ${obsdatabase}/ioda.icec.cat_l2.emc_LARGE.nc ${obsdatabase}/icec-tmp.nc
+   #ncks --mk_rec_dmn nlocs ${obsdatabase}/ioda.icec.cat_l2.emc_LARGE.nc ${obsdatabase}/icec-tmp.nc
    # Subsample
-   ncks -F -d nlocs,1,,5 ${obsdatabase}/icec-tmp.nc ${DATADIR}/ioda.icec.cat_l2.emc.nc
-   rm ${obsdatabase}/icec-tmp.nc
-   rm ${obsdatabase}/ioda.icec.cat_l2.emc_LARGE.nc
+   #ncks -F -d nlocs,1,,5 ${obsdatabase}/icec-tmp.nc ${DATADIR}/ioda.icec.cat_l2.emc.nc
+   #rm ${obsdatabase}/icec-tmp.nc
+   #rm ${obsdatabase}/ioda.icec.cat_l2.emc_LARGE.nc
```
Comment (flampouris) [inline scripts/SetupJoCostFunction.sh]: Delete lines 59:66.

Comment (guillaumevernieres) [reply scripts/SetupJoCostFunction.sh]: done
